services:
  - type: web
    name: esports-analyzer
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r req.txt
    startCommand: gunicorn app.app:app --workers 1 --threads 8 --timeout 0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
